version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - npm run build || echo "No build step needed"
  post_build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r deploy.zip . -x "node_modules/*"
artifacts:
  files:
    - deploy.zip
